view: user_facts {

  derived_table: {
    sql:
      SELECT
        user_id,
        COUNT(DISTINCT order_id) AS lifetime_order_count,
        SUM(sale_price) AS lifetime_spend
      FROM `bigquery-public-data.thelook_ecommerce.order_items`
      GROUP BY user_id
    ;;
  }

  dimension: user_id {
    label: "User ID"
    type: number
    primary_key: yes
    sql: ${TABLE}.user_id ;;
  }

  dimension: lifetime_order_count {
    label: "Lifetime Order Count"
    description: "Total distinct orders placed by the user"
    type: number
    sql: ${TABLE}.lifetime_order_count ;;
  }

  dimension: lifetime_spend {
    label: "Lifetime Spend"
    description: "Total lifetime sales generated by the user"
    type: number
    sql: ${TABLE}.lifetime_spend ;;
    value_format_name: usd
  }

  measure: average_lifetime_spend {
    label: "Average Lifetime Spend"
    description: "Average lifetime spend across the selected users"
    type: average
    sql: ${lifetime_spend} ;;
    value_format_name: usd
  }

  measure: average_lifetime_order_count {
    label: "Average Lifetime Order Count"
    description: "Average number of lifetime orders across the selected users"
    type: average
    sql: ${lifetime_order_count} ;;
    value_format_name: decimal_2
  }

  measure: user_count {
    label: "User Count"
    type: count
    drill_fields: [user_id, lifetime_spend, lifetime_order_count]
  }
}
